controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.35 #0.5
  min_vel_x: 0.01 #0.01
  max_vel_y: 0.0 #diff drive robot
  min_vel_y: 0.0 #diff drive robot
  min_vel_theta: -2.5 #2.57 #1.5
  max_vel_theta: 2.5 #2.57 #1.5

  min_in_place_vel_theta: 0.05 #1.314

  acc_lim_theta: 2.0
  acc_lim_x: 0.5
  acc_lim_y: 0.0

  sim_time: 2.0

  vx_samples: 5.0
  vtheta_samples: 40.0

  pdist_scale: 0.6 #0.6
  gdist_scale: 1.8 #0.8
  occdist_scale: 0.03 #0.02

  holonomic_robot: false
